In [24]:
import pandas as pd
df = pd.read_csv("C:/Users/salaz/OneDrive/Desktop/Ciencia de Datos/Proyecto NFL/Data/Base de Datos Limpia")
df

,Year,Name,College,POS,Height (in),Weight (lbs),Hand Size (in),Arm Length (in),Wonderlic,40 Yard,Bench Press,Vert Leap (in),Broad Jump (in),Shuttle,3Cone,60Yd Shuttle
0,1987.0,Mike Adams,Arizona State,CB,74.00,198.0,8.50,30.50,24.0,4.42,13.0,32.0,118.0,4.60,9.99,11.65
1,1987.0,John Adickes,Florida State,C,74.00,266.0,10.25,30.00,24.0,4.80,25.0,26.5,103.0,4.60,9.99,11.65
2,1987.0,Tommy Agee,Auburn,FB,74.00,217.0,9.00,30.75,24.0,9.99,15.0,32.0,113.0,9.99,9.99,11.65
3,1987.0,David Alexander,Florida State,C,75.00,279.0,10.50,32.25,24.0,5.13,22.0,27.5,113.0,4.33,9.99,11.65
4,1987.0,Lyneal Alston,Southern Mississippi,WR,72.10,202.0,10.00,33.00,24.0,4.64,7.0,32.0,114.0,4.52,9.99,11.85
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10427,2015.0,Steve Smith,Michigan State,FS,72.63,208.0,10.38,32.25,24.0,4.65,20.0,32.0,119.0,4.33,7.09,11.65
10428,2001.0,Steve Smith,Penn State,CB,72.30,199.0,8.50,31.00,24.0,4.53,20.0,34.5,113.0,4.27,7.21,11.84
10429,2014.0,James Morris,Iowa,ILB,72.88,241.0,9.13,30.75,24.0,4.80,18.0,34.5,116.0,4.36,6.94,11.65
10430,1991.0,Todd Scott,Southwestern Louisiana,CB,70.40,204.0,9.63,31.00,24.0,4.65,14.0,33.0,113.0,4.52,9.99,11.41
10431,1993.0,Mark Szlachcic,Bowling Green (OH),WR,75.90,200.0,8.88,33.00,24.0,4.96,20.0,26.0,106.0,4.47,9.99,12.27

In [25]:

df.columns # de qui saco los nombres de las columnas para facilitar el filtrado

Index(['Year', 'Name', 'College', 'POS', 'Height (in)', 'Weight (lbs)',
       'Hand Size (in)', 'Arm Length (in)', 'Wonderlic', '40 Yard',
       'Bench Press', 'Vert Leap (in)', 'Broad Jump (in)', 'Shuttle', '3Cone',
       '60Yd Shuttle'],
      dtype='object')

In [ ]:
def valoresreales(df, col):
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    limINF = Q1 - 2 * IQR #Multiplico por 2 para quedarme con más de 8781 registros, si lo hacia con el normal de 1.5 se reducia en más de mil
    limSup = Q3 + 2 * IQR

    antes = len(df)
    df_filtrado = df[(df[col] >= limINF) & (df[col] <= limSup)]
    despues = len(df_filtrado)

    print(f"{col}: antes = {antes}, después = {despues}, eliminados = {antes - despues}")

    return df_filtrado

In [27]:
cols_seguras = [
    "40 Yard",
    "Bench Press",
    "Vert Leap (in)",
    "Broad Jump (in)",
    "Weight (lbs)",
    "Height (in)"
]
for c in cols_seguras:
    df = valoresreales(df, c)

40 Yard: antes = 10432, después = 9554, eliminados = 878
Bench Press: antes = 9554, después = 8856, eliminados = 698
Vert Leap (in): antes = 8856, después = 8828, eliminados = 28
Broad Jump (in): antes = 8828, después = 8781, eliminados = 47
Weight (lbs): antes = 8781, después = 8781, eliminados = 0
Height (in): antes = 8781, después = 8781, eliminados = 0

In [28]:
df.shape

(8781, 16)

In [29]:
df.isna().sum()

Year               0
Name               0
College            0
POS                0
Height (in)        0
Weight (lbs)       0
Hand Size (in)     0
Arm Length (in)    0
Wonderlic          0
40 Yard            0
Bench Press        0
Vert Leap (in)     0
Broad Jump (in)    0
Shuttle            0
3Cone              0
60Yd Shuttle       0
dtype: int64

In [34]:
df.describe()

,Year,Height (in),Weight (lbs),Hand Size (in),Arm Length (in),Wonderlic,40 Yard,Bench Press,Vert Leap (in),Broad Jump (in),Shuttle,3Cone,60Yd Shuttle
count,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000,8781.000000
mean,2002.745701,73.764864,239.775424,9.524603,32.230317,24.005125,4.823943,19.893406,32.074331,112.697187,5.599100,8.712257,11.659153
std,8.880818,2.568284,43.099220,0.561043,1.326168,1.618260,0.298863,4.090717,3.744442,7.948480,2.302446,1.364081,0.239406
min,1987.000000,65.250000,144.000000,7.130000,26.880000,4.000000,4.210000,10.000000,21.000000,90.000000,3.730000,6.340000,10.430000
25%,1995.000000,72.000000,205.000000,9.250000,31.500000,24.000000,4.590000,18.000000,30.000000,109.000000,4.260000,7.270000,11.650000
50%,2002.000000,74.000000,232.000000,9.500000,32.250000,24.000000,4.770000,20.000000,32.000000,113.000000,4.500000,9.990000,11.650000
75%,2011.000000,75.600000,270.000000,9.880000,33.000000,24.000000,5.010000,22.000000,34.500000,117.000000,4.880000,9.990000,11.650000
max,2017.000000,81.630000,385.000000,11.880000,37.750000,48.000000,6.070000,30.000000,43.500000,135.000000,9.990000,9.990000,13.910000

In [31]:
df.to_csv("NFL_Csv_Cluster", index=False)